import js from '@eslint/js';
import globals from 'globals';
import vue from 'eslint-plugin-vue';

const foundationFiles = [
  'src/main.js',
  'vite.config.js',
  'src/app/AppShell.vue',
  'src/app/operatorExperience.js',
  'src/app/workspaceRegistry.js',
  'src/composables/useNumberFormat.js',
  'src/i18n/index.js',
  'src/locales/**/*.js',
  'src/components/EmptyState.vue',
  'src/components/ErrorState.vue',
  'src/components/KpiCard.vue',
  'src/components/LoadingState.vue',
  'src/components/MiniSparkline.vue',
  'src/components/ProductionEvidenceValidationPanel.vue',
  'src/components/USDJPYStrategyPolicyPanel.vue',
  'src/utils/displayText.js',
  'src/utils/redactSensitiveEvidence.js',
  'src/workspaces/shared/JsonPreview.vue',
  'src/workspaces/shared/LedgerTable.vue',
  'src/workspaces/dashboard/DashboardUpgradePanel.vue',
  'src/workspaces/dashboard/DashboardWorkspace.vue',
  'src/workspaces/mt5/Mt5Workspace.vue',
  'src/workspaces/mt5/mt5Model.js',
  'src/services/api.js',
  'src/services/apiClient.js',
  'src/services/automationChainApi.js',
  'src/services/backtestAiApi.js',
  'src/services/caseMemoryApi.js',
  'src/services/domainApi.js',
  'src/services/gaFactoryApi.js',
  'src/services/gaStabilityApi.js',
  'src/services/phase1Api.js',
  'src/services/phase2Api.js',
  'src/services/phase3Api.js',
  'src/services/productionEvidenceApi.js',
  'src/services/strategyGaFactoryApi.js',
  'src/services/telegramGatewayOpsApi.js',
  'src/services/usdjpyStrategyLabApi.js',
  'src/workspaces/backtest-ai/BacktestAiWorkspace.vue',
  'src/workspaces/phase1/AiAnalysisWorkspace.vue',
  'src/workspaces/phase1/Phase1Workspace.vue',
  'src/workspaces/phase1/kline/KlineChart.vue',
  'src/workspaces/phase1/kline/KlineToolbar.vue',
  'src/workspaces/phase1/kline/KlineWorkspace.vue',
  'src/workspaces/phase1/kline/SignalOverlay.vue',
  'src/workspaces/phase2/Phase2OperationsWorkspace.vue',
  'src/workspaces/phase3/Phase3Workspace.vue',
  'src/workspaces/phase3/ai/AiV2DebateWorkspace.vue',
  'src/workspaces/phase3/vibe/VibeCodingWorkspace.vue',
  'scripts/frontend_api_client_guard.mjs',
  'scripts/frontend_code_splitting_guard.mjs',
  'scripts/responsive_check.mjs',
  'scripts/frontend_ux_foundation_guard.mjs',
  'scripts/frontend_responsive_hardening_guard.mjs',
  'scripts/frontend_production_evidence_guard.mjs',
  'scripts/frontend_usdjpy_strategy_lab_guard.mjs',
  'tests/frontend_api_client_guard.test.mjs',
  'tests/frontend_code_splitting_guard.test.mjs',
  'tests/frontend_ux_foundation_guard.test.mjs',
  'tests/frontend_responsive_hardening_guard.test.mjs',
  'tests/frontend_production_evidence_guard.test.mjs',
  'tests/frontend_usdjpy_strategy_lab_guard.test.mjs',
  'tests/frontend_sensitive_fixture_guard.test.mjs',
  'tests/backtest_ai_api.test.mjs',
  'tests/legacy_dashboard_api.test.mjs',
  'tests/number_format.test.mjs',
  'tests/unit/**/*.test.js',
];

export default [
  {
    ignores: ['node_modules/**', 'dist/**', 'runtime/**', 'coverage/**'],
  },
  js.configs.recommended,
  ...vue.configs['flat/recommended'],
  {
    files: foundationFiles,
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      'vue/max-attributes-per-line': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/no-v-html': 'off',
      'vue/require-default-prop': 'off',
      'vue/html-self-closing': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/html-indent': 'off',
      'vue/singleline-html-element-content-newline': 'off',
    },
  },
];
